source_name : "The Guardian"
api_key_name : "guardian_api_key"
base_url : "https://content.guardianapis.com/search"
n_days_fill : 1000
output_folder : "data/"
output_file : "guardian_data"
enhancement_model : "facebook/bart-large-mnli"
cuisines:
  - "italian"
  - "indian"
  - "asian"
  - "mexican"
  - "european"
  - "british"
  - "american"
  - "mediterranean"
  - "middle eastern"
  - "african"
  - "other"